// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gorilla/mux"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for NewTodoStatus.
const (
	NewTodoStatusDone       NewTodoStatus = "done"
	NewTodoStatusInProgress NewTodoStatus = "in_progress"
	NewTodoStatusTodo       NewTodoStatus = "todo"
)

// Valid indicates whether the value is a known member of the NewTodoStatus enum.
func (e NewTodoStatus) Valid() bool {
	switch e {
	case NewTodoStatusDone:
		return true
	case NewTodoStatusInProgress:
		return true
	case NewTodoStatusTodo:
		return true
	default:
		return false
	}
}

// Defines values for TodoStatus.
const (
	TodoStatusDone       TodoStatus = "done"
	TodoStatusInProgress TodoStatus = "in_progress"
	TodoStatusTodo       TodoStatus = "todo"
)

// Valid indicates whether the value is a known member of the TodoStatus enum.
func (e TodoStatus) Valid() bool {
	switch e {
	case TodoStatusDone:
		return true
	case TodoStatusInProgress:
		return true
	case TodoStatusTodo:
		return true
	default:
		return false
	}
}

// Defines values for UpdateTodoStatus.
const (
	UpdateTodoStatusDone       UpdateTodoStatus = "done"
	UpdateTodoStatusInProgress UpdateTodoStatus = "in_progress"
	UpdateTodoStatusTodo       UpdateTodoStatus = "todo"
)

// Valid indicates whether the value is a known member of the UpdateTodoStatus enum.
func (e UpdateTodoStatus) Valid() bool {
	switch e {
	case UpdateTodoStatusDone:
		return true
	case UpdateTodoStatusInProgress:
		return true
	case UpdateTodoStatusTodo:
		return true
	default:
		return false
	}
}

// Defines values for ListTodosParamsStatus.
const (
	ListTodosParamsStatusDone       ListTodosParamsStatus = "done"
	ListTodosParamsStatusInProgress ListTodosParamsStatus = "in_progress"
	ListTodosParamsStatusTodo       ListTodosParamsStatus = "todo"
)

// Valid indicates whether the value is a known member of the ListTodosParamsStatus enum.
func (e ListTodosParamsStatus) Valid() bool {
	switch e {
	case ListTodosParamsStatusDone:
		return true
	case ListTodosParamsStatusInProgress:
		return true
	case ListTodosParamsStatusTodo:
		return true
	default:
		return false
	}
}

// Defines values for ListTodosParamsSort.
const (
	CreatedAt      ListTodosParamsSort = "created_at"
	MinusCreatedAt ListTodosParamsSort = "-created_at"
	Title          ListTodosParamsSort = "title"
)

// Valid indicates whether the value is a known member of the ListTodosParamsSort enum.
func (e ListTodosParamsSort) Valid() bool {
	switch e {
	case CreatedAt:
		return true
	case MinusCreatedAt:
		return true
	case Title:
		return true
	default:
		return false
	}
}

// Credentials Credentials for signup and login.
type Credentials struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// Error Uniform error body for every non-2xx response.
type Error struct {
	// Message Human-readable explanation of what went wrong.
	//
	// Example: todo not found
	Message string `json:"message"`
}

// NewTodo Body for POST /todos and PUT /todos/{id} (full replace).
type NewTodo struct {
	Description *string `json:"description,omitempty"`

	// Status Defaults to `todo` when omitted.
	Status *NewTodoStatus `json:"status,omitempty"`

	// Title Example: Read the OpenAPI 3.0 spec
	Title string `json:"title"`
}

// NewTodoStatus Defaults to `todo` when omitted.
type NewTodoStatus string

// Pagination Where this page sits in the full result set.
type Pagination struct {
	// Limit Page size actually used (after applying the default).
	Limit int `json:"limit"`

	// Offset Number of items skipped before this page.
	Offset int `json:"offset"`

	// Total Total items matching the filter (before paging).
	Total int `json:"total"`
}

// Todo A todo as returned by the API (responses only).
type Todo struct {
	CreatedAt   *time.Time          `json:"created_at,omitempty"`
	Description *string             `json:"description,omitempty"`
	Id          *openapi_types.UUID `json:"id,omitempty"`

	// Status Lifecycle of a todo.
	Status    TodoStatus `json:"status"`
	Title     string     `json:"title"`
	UpdatedAt *time.Time `json:"updated_at,omitempty"`
}

// TodoList A page of todos plus pagination metadata.
type TodoList struct {
	// Items Todos in this page.
	Items []Todo `json:"items"`

	// Pagination Where this page sits in the full result set.
	Pagination Pagination `json:"pagination"`
}

// TodoStatus Lifecycle of a todo.
type TodoStatus string

// Token JWT issued by POST /login.
type Token struct {
	Token string `json:"token"`
}

// UpdateTodo Body for PATCH /todos/{id}. Omitted fields keep their values.
type UpdateTodo struct {
	Description *string           `json:"description,omitempty"`
	Status      *UpdateTodoStatus `json:"status,omitempty"`
	Title       *string           `json:"title,omitempty"`
}

// UpdateTodoStatus defines model for UpdateTodo.Status.
type UpdateTodoStatus string

// User defines model for User.
type User struct {
	Email openapi_types.Email `json:"email"`
	Id    openapi_types.UUID  `json:"id"`
}

// Limit defines model for Limit.
type Limit = int

// Offset defines model for Offset.
type Offset = int

// BadRequest Uniform error body for every non-2xx response.
type BadRequest = Error

// NotFound Uniform error body for every non-2xx response.
type NotFound = Error

// Unauthorized Uniform error body for every non-2xx response.
type Unauthorized = Error

// ListTodosParams defines parameters for ListTodos.
type ListTodosParams struct {
	// Limit Page size, 1-100.
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset Number of items to skip before this page.
	Offset *Offset `form:"offset,omitempty" json:"offset,omitempty"`

	// Status Only return todos with this status. Omit for all.
	Status *ListTodosParamsStatus `form:"status,omitempty" json:"status,omitempty"`

	// Sort Sort order. `-` prefix means descending.
	Sort *ListTodosParamsSort `form:"sort,omitempty" json:"sort,omitempty"`

	// XRequestID Optional client-supplied ID for tracing requests.
	XRequestID *openapi_types.UUID `json:"X-Request-ID,omitempty"`
}

// ListTodosParamsStatus defines parameters for ListTodos.
type ListTodosParamsStatus string

// ListTodosParamsSort defines parameters for ListTodos.
type ListTodosParamsSort string

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = Credentials

// SignupJSONRequestBody defines body for Signup for application/json ContentType.
type SignupJSONRequestBody = Credentials

// CreateTodoJSONRequestBody defines body for CreateTodo for application/json ContentType.
type CreateTodoJSONRequestBody = NewTodo

// UpdateTodoJSONRequestBody defines body for UpdateTodo for application/json ContentType.
type UpdateTodoJSONRequestBody = UpdateTodo

// ReplaceTodoJSONRequestBody defines body for ReplaceTodo for application/json ContentType.
type ReplaceTodoJSONRequestBody = NewTodo

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Login Log in and receive a JWT bearer token
	// (POST /login)
	Login(w http.ResponseWriter, r *http.Request)
	// Signup Register a new user
	// (POST /signup)
	Signup(w http.ResponseWriter, r *http.Request)
	// ListTodos List your todos
	// (GET /todos)
	ListTodos(w http.ResponseWriter, r *http.Request, params ListTodosParams)
	// CreateTodo Create a todo
	// (POST /todos)
	CreateTodo(w http.ResponseWriter, r *http.Request)
	// DeleteTodo Delete a todo
	// (DELETE /todos/{id})
	DeleteTodo(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// GetTodo Get one todo
	// (GET /todos/{id})
	GetTodo(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// UpdateTodo Update a todo partially (PATCH)
	// (PATCH /todos/{id})
	UpdateTodo(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// ReplaceTodo Replace a todo entirely (PUT)
	// (PUT /todos/{id})
	ReplaceTodo(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Signup operation middleware
func (siw *ServerInterfaceWrapper) Signup(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Signup(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTodos operation middleware
func (siw *ServerInterfaceWrapper) ListTodos(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTodosParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status", r.URL.Query(), &params.Status, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "sort"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		}
		return
	}

	headers := r.Header

	// ------------- Optional header parameter "X-Request-ID" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Request-ID")]; found {
		var XRequestID openapi_types.UUID
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "X-Request-ID", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Request-ID", valueList[0], &XRequestID, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: "uuid"})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "X-Request-ID", Err: err})
			return
		}

		params.XRequestID = &XRequestID

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTodos(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTodo operation middleware
func (siw *ServerInterfaceWrapper) CreateTodo(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTodo(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteTodo operation middleware
func (siw *ServerInterfaceWrapper) DeleteTodo(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", mux.Vars(r)["id"], &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteTodo(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTodo operation middleware
func (siw *ServerInterfaceWrapper) GetTodo(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", mux.Vars(r)["id"], &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTodo(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTodo operation middleware
func (siw *ServerInterfaceWrapper) UpdateTodo(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", mux.Vars(r)["id"], &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTodo(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReplaceTodo operation middleware
func (siw *ServerInterfaceWrapper) ReplaceTodo(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", mux.Vars(r)["id"], &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReplaceTodo(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{})
}

type GorillaServerOptions struct {
	BaseURL          string
	BaseRouter       *mux.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r *mux.Router) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r *mux.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options GorillaServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = mux.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.HandleFunc(options.BaseURL+"/signup", wrapper.Signup).Methods(http.MethodPost)

	r.HandleFunc(options.BaseURL+"/login", wrapper.Login).Methods(http.MethodPost)

	r.HandleFunc(options.BaseURL+"/todos", wrapper.ListTodos).Methods(http.MethodGet)

	r.HandleFunc(options.BaseURL+"/todos", wrapper.CreateTodo).Methods(http.MethodPost)

	r.HandleFunc(options.BaseURL+"/todos/{id}", wrapper.DeleteTodo).Methods(http.MethodDelete)

	r.HandleFunc(options.BaseURL+"/todos/{id}", wrapper.GetTodo).Methods(http.MethodGet)

	r.HandleFunc(options.BaseURL+"/todos/{id}", wrapper.UpdateTodo).Methods(http.MethodPatch)

	r.HandleFunc(options.BaseURL+"/todos/{id}", wrapper.ReplaceTodo).Methods(http.MethodPut)

	return r
}

type BadRequestJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type LoginRequestObject struct {
	Body *LoginJSONRequestBody
}

type LoginResponseObject interface {
	VisitLoginResponse(w http.ResponseWriter) error
}

type Login200JSONResponse Token

func (response Login200JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Login401JSONResponse struct{ UnauthorizedJSONResponse }

func (response Login401JSONResponse) VisitLoginResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type SignupRequestObject struct {
	Body *SignupJSONRequestBody
}

type SignupResponseObject interface {
	VisitSignupResponse(w http.ResponseWriter) error
}

type Signup201JSONResponse User

func (response Signup201JSONResponse) VisitSignupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type Signup409JSONResponse Error

func (response Signup409JSONResponse) VisitSignupResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type ListTodosRequestObject struct {
	Params ListTodosParams
}

type ListTodosResponseObject interface {
	VisitListTodosResponse(w http.ResponseWriter) error
}

type ListTodos200JSONResponse TodoList

func (response ListTodos200JSONResponse) VisitListTodosResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListTodos400JSONResponse struct{ BadRequestJSONResponse }

func (response ListTodos400JSONResponse) VisitListTodosResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListTodos401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListTodos401JSONResponse) VisitListTodosResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTodoRequestObject struct {
	Body *CreateTodoJSONRequestBody
}

type CreateTodoResponseObject interface {
	VisitCreateTodoResponse(w http.ResponseWriter) error
}

type CreateTodo201ResponseHeaders struct {
	Location *string
}

type CreateTodo201JSONResponse struct {
	Body    Todo
	Headers CreateTodo201ResponseHeaders
}

func (response CreateTodo201JSONResponse) VisitCreateTodoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	if response.Headers.Location != nil {
		w.Header().Set("Location", fmt.Sprint(*response.Headers.Location))
	}
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTodo400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateTodo400JSONResponse) VisitCreateTodoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateTodo401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateTodo401JSONResponse) VisitCreateTodoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteTodoRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type DeleteTodoResponseObject interface {
	VisitDeleteTodoResponse(w http.ResponseWriter) error
}

type DeleteTodo204Response struct {
}

func (response DeleteTodo204Response) VisitDeleteTodoResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteTodo401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteTodo401JSONResponse) VisitDeleteTodoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteTodo404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteTodo404JSONResponse) VisitDeleteTodoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetTodoRequestObject struct {
	Id openapi_types.UUID `json:"id"`
}

type GetTodoResponseObject interface {
	VisitGetTodoResponse(w http.ResponseWriter) error
}

type GetTodo200JSONResponse Todo

func (response GetTodo200JSONResponse) VisitGetTodoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetTodo401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetTodo401JSONResponse) VisitGetTodoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetTodo404JSONResponse struct{ NotFoundJSONResponse }

func (response GetTodo404JSONResponse) VisitGetTodoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateTodoRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *UpdateTodoJSONRequestBody
}

type UpdateTodoResponseObject interface {
	VisitUpdateTodoResponse(w http.ResponseWriter) error
}

type UpdateTodo200JSONResponse Todo

func (response UpdateTodo200JSONResponse) VisitUpdateTodoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateTodo400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateTodo400JSONResponse) VisitUpdateTodoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateTodo401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateTodo401JSONResponse) VisitUpdateTodoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateTodo404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateTodo404JSONResponse) VisitUpdateTodoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ReplaceTodoRequestObject struct {
	Id   openapi_types.UUID `json:"id"`
	Body *ReplaceTodoJSONRequestBody
}

type ReplaceTodoResponseObject interface {
	VisitReplaceTodoResponse(w http.ResponseWriter) error
}

type ReplaceTodo200JSONResponse Todo

func (response ReplaceTodo200JSONResponse) VisitReplaceTodoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ReplaceTodo400JSONResponse struct{ BadRequestJSONResponse }

func (response ReplaceTodo400JSONResponse) VisitReplaceTodoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ReplaceTodo401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ReplaceTodo401JSONResponse) VisitReplaceTodoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ReplaceTodo404JSONResponse struct{ NotFoundJSONResponse }

func (response ReplaceTodo404JSONResponse) VisitReplaceTodoResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Login Log in and receive a JWT bearer token
	// (POST /login)
	Login(ctx context.Context, request LoginRequestObject) (LoginResponseObject, error)
	// Signup Register a new user
	// (POST /signup)
	Signup(ctx context.Context, request SignupRequestObject) (SignupResponseObject, error)
	// ListTodos List your todos
	// (GET /todos)
	ListTodos(ctx context.Context, request ListTodosRequestObject) (ListTodosResponseObject, error)
	// CreateTodo Create a todo
	// (POST /todos)
	CreateTodo(ctx context.Context, request CreateTodoRequestObject) (CreateTodoResponseObject, error)
	// DeleteTodo Delete a todo
	// (DELETE /todos/{id})
	DeleteTodo(ctx context.Context, request DeleteTodoRequestObject) (DeleteTodoResponseObject, error)
	// GetTodo Get one todo
	// (GET /todos/{id})
	GetTodo(ctx context.Context, request GetTodoRequestObject) (GetTodoResponseObject, error)
	// UpdateTodo Update a todo partially (PATCH)
	// (PATCH /todos/{id})
	UpdateTodo(ctx context.Context, request UpdateTodoRequestObject) (UpdateTodoResponseObject, error)
	// ReplaceTodo Replace a todo entirely (PUT)
	// (PUT /todos/{id})
	ReplaceTodo(ctx context.Context, request ReplaceTodoRequestObject) (ReplaceTodoResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	if options.RequestErrorHandlerFunc == nil {
		options.RequestErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	if options.ResponseErrorHandlerFunc == nil {
		options.ResponseErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
	}
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// Login operation middleware
func (sh *strictHandler) Login(w http.ResponseWriter, r *http.Request) {
	var request LoginRequestObject

	var body LoginJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Login(ctx, request.(LoginRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Login")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(LoginResponseObject); ok {
		if err := validResponse.VisitLoginResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Signup operation middleware
func (sh *strictHandler) Signup(w http.ResponseWriter, r *http.Request) {
	var request SignupRequestObject

	var body SignupJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Signup(ctx, request.(SignupRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Signup")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SignupResponseObject); ok {
		if err := validResponse.VisitSignupResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ListTodos operation middleware
func (sh *strictHandler) ListTodos(w http.ResponseWriter, r *http.Request, params ListTodosParams) {
	var request ListTodosRequestObject

	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListTodos(ctx, request.(ListTodosRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListTodos")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListTodosResponseObject); ok {
		if err := validResponse.VisitListTodosResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateTodo operation middleware
func (sh *strictHandler) CreateTodo(w http.ResponseWriter, r *http.Request) {
	var request CreateTodoRequestObject

	var body CreateTodoJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateTodo(ctx, request.(CreateTodoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateTodo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateTodoResponseObject); ok {
		if err := validResponse.VisitCreateTodoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteTodo operation middleware
func (sh *strictHandler) DeleteTodo(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request DeleteTodoRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteTodo(ctx, request.(DeleteTodoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteTodo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteTodoResponseObject); ok {
		if err := validResponse.VisitDeleteTodoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetTodo operation middleware
func (sh *strictHandler) GetTodo(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request GetTodoRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetTodo(ctx, request.(GetTodoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetTodo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetTodoResponseObject); ok {
		if err := validResponse.VisitGetTodoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// UpdateTodo operation middleware
func (sh *strictHandler) UpdateTodo(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request UpdateTodoRequestObject

	request.Id = id

	var body UpdateTodoJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateTodo(ctx, request.(UpdateTodoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateTodo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(UpdateTodoResponseObject); ok {
		if err := validResponse.VisitUpdateTodoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ReplaceTodo operation middleware
func (sh *strictHandler) ReplaceTodo(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	var request ReplaceTodoRequestObject

	request.Id = id

	var body ReplaceTodoJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ReplaceTodo(ctx, request.(ReplaceTodoRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ReplaceTodo")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ReplaceTodoResponseObject); ok {
		if err := validResponse.VisitReplaceTodoResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"1Fpvb9s40v8qAz0P0DSnyE7aF3u+N9cm3d0ssptc4mAPaII1I40lbilSS1Jx3SLAfYj7hPdJDkNSsmQr",
	"TZ20Xdw76w+Hw5nfzG9m5I9RqspKSZTWRJOPUcU0K9GidlcnvOSWfmRoUs0ry5WMJtEZyxEM/4Ax7O/t",
	"j8dJFEecHvxRo15GcSRZidEkEm55HJm0wJJ5OXNWCxtNDsZxVLL3vKzLaLI/pisuw1Uc2WVF67m0mKOO",
	"7u7i6HQ+Nzigyy91eYMa1By4xdKAVWDe8QpucK40gi24gYrleJ+OyssdVLKr1XhAq7s40mgqJQ06c71m",
	"2Tn+UaNxeqZKWpTuJ6sqwVNGKo9+N6T3x85+/69xHk2i/xutXDHyT83ojdYqbNU/d9gI5owLzOCWCZ65",
	"DWDnhmVwo7IlKA0rfz5Pors4+kXZ71Uts89QEN+zshJIP0s0huV0eKsyBVJZmDspd/HTz2FUrVNcCYUd",
	"pYFbuEGhZO48yqSyBWqoDWp/jkvJalsozT/go89ScmO4zMlMXDoDwqsg1FuyQJaRo598yJ83d7pBplGD",
	"Ve9QJg7hQQptcqgxQ2k5E+6SZRknSUycaVWhtpzwNmfC4PpOnZUwVxoMz2VdAZMZCJVzSWFQdYR8jLBk",
	"XNCPudIls9Ek3HHYP0GZ2yKavGjRb6zmMiebVMyYhdJZb21704V3s3z/4LueuO82xLlQ+qPmmtz5tlWh",
	"FXfdrlA3v2NqSQFv7u3scyk56QpIa32UkJnwFvUSpJJ7B+/fQxPUm8ZqwbOehn6sSyb3NLKM3QgEfF8J",
	"Jj2K1BwWBbOwQGlhoZXMSW6LyPWQesg0jQpDFvkFF1OVqS1t8rqxwtnpxRRGpI9xiDm7bC5HH3l2Bzvz",
	"WgjQWAmW4vNN6/TEfuwC4GA8Hg9AyFhma9PLuc4c0bqKR/6xSwYzemMGiwIlqJJbi5kzqKQ0/bZZz+Vv",
	"lVa5RmNImpJdi600sNz6tLDyxzmyDGyBcFqhfHV2DC+SMZgK0z6mDwJptRh/yHF+qyG3nbGce7Bs6blf",
	"C+xyHBhuDXDptA++MrWwYNBueks8QO7AUlszIZaUdjPYYXOLGii7LimX0R7Baw4K6+wYN9T6IGUTX1eY",
	"DVL2plSrLBObQqd0OwgsmU2LRsc5F6T3TpBeka3zQY3X/eU2itsqJhxnyIGPCLpX4OKeGdBoay3p/Eun",
	"MEFup60rQEmxHIi1VCOzmP3GbC//ZszinuUlRnQYlp1KsYwmVtc4AP6t45X3k31d8+xz9lmF+afYk4x4",
	"4d/sBuZWIRdHdZU90S5rMHBH9Nq0J4m75u/teR86TrgvCrdCiItpNQefkStRGw9fzyslWpYxyzax4aJg",
	"KERIjEsP3aK4efkh3ziv+LMxrdnS1wDdzPUpCZ0ct2Fhp0FP2H1mvOgQRvdoJ3yO6TIVzlzMGezxnDCl",
	"mmxLZ/306xS4MbUPY0+k9xRcthH/AF2414YMceng9iSifzU9/LFL7QmceiaFOUeRGXiHWFE24ppaixpN",
	"4gvC7h77X5D/n8je2/Lypk0NPlxKfm7h/Jl58zPyjpe4CQKyHaa15nZ5QQHmNfI9xU+/TlcX3zd70t14",
	"g+qNRcc5Dmw9JupCGI6UfGaBy1TUmV9wFb32DcxVBJXGOX8P//nXv+FiwfIcNVweA8syQ20c4W2p6uRK",
	"Nk02HcRrtzJCYW3lOycu56rp6FjqkmZo1T/U7zhlWy3CAjMZjXJui/omSVU5ouc5tyOBTMs9VaFkFd/g",
	"uegVuBeoPiCqtVSbZ1gqaaxmFk2v9psjs7VGQ0d4JgSUiDZUWFdSIxOwUFpkE9jddQXX4fnl0e5uDBWz",
	"xciNGka+i+x04jFo37xfyVXbTjdr45qHVfaMgfJK4+m4k/1j38GQDk2hQBV7cxVaV5NcySv5j5qn78Cq",
	"Wk+uJMB+AjPvXd8czqio1phzY1HHdDLZvODc757naIGRNgmJOEjgUJDQ3d2mY8bdXbJLFwAyg6qPMLf4",
	"RQJngi1hwW3hHs18IpoByqxSXFrjwSJ4itJgBwE/H087Ye8YgXwYxdEtauPdu5+Mk7ErPwMAJtGLZJy8",
	"cARjCxco/mBu3qU8L1NgO8MeZ0Qn7rGPRzSW8uYXm+h0e/u7ftBTObI+UzoYj7/Y1p7YBuYT7rxg6jRF",
	"Y+a1cCOWl+P9+wS2Go56c5huWoomb6/jyNRlyfTSb0H48CBNkd+ix1NvEEL5gOWG0h/hKromiQGm93vr",
	"wj/f1l2h43NWdnHoDNkq/MrP1MIEhSBGPNhJ/BHL2N+DEMo/3XHFJEqV1pjavUJpg3s3zFrUS2/7r4ST",
	"/S+GE0eGAzCh+xAq3wCRv379SecbMjcwQWX7sk1UToNP4O08vAcMJC7c5HAYXS73kHL5UK967ijRc0LK",
	"hED9zPh6PCa5bgLLtbFEmaEbTuCiriqlrQFf34QWlAiH4O/7yE4u99luLQNxY1297lC1msm/HTbi6pWR",
	"n9nfxQ++GCbq9Gb/zNQbhVogtB4hVfPmRL5cdNTOhLhvtN42SysAPKbM21TwQmkLSmeoE5jtzZoCpEQm",
	"DdCrKDPux2yDeil9z8A/2uv1dY22vZv9V9aHOvcrfVr5uhJSwVHaPVNTqGAGx0fOkFazlCASkphptQ9T",
	"6Fb9f+6F2f/e8VHvGA/Vl9dflVpCjzsQwGuNbMgc44fJpfM95fF8tGIgbiyVcdqr0ckGPtCuqZ8dJJhD",
	"5/Gpx+zjSYYKxDWOESI0XF1+WZvxaW7RzR9jyFGSXlQiZhgDJ9ElSgsFk5mgBLHqqdaCq6mZLgpeNWMm",
	"ZyD3hYutKfaaaYTw7Qt23Fo/iOrq2Yg8oXK6qZi3obhmXP2N6W2158a3E8dsMC3QkYab0PHOhC6MVm9U",
	"toxdLnfl64nyaszWy2/w1SwwS40Q9UcMUsGM4Smcv7mYQqrkLXF8wwGhanefXoPQTUBcnp+4WPJKimXD",
	"yO3UY2WF9Qxw9+dEnjdsmMsMxF1Lw24W4U8s0OJmJB65+20k9gDyctNU/vUsgYPxS3KkY/HW5v4DmS96",
	"4S+AZWWXzrePLX9p0cuHF7XfYPtW8sreb6W4qVD6JvkB7bA9xl89YKauryPQ/Rn2+gEtKIn3m2utbhrW",
	"/ZmBy8vjo5ZtqUdccW2Yb3cz05aMWzGbFgNfWdwEjlIqpAWTeRg7hOlbpdFQWu/km78137oGJnRprTW9",
	"HiZ1cIEIs9WUcOaAviiWMOtN8GZQurbEQIEah6rQzqTxKcRnLNP22PYp5mem3wWwA3Nj6Q5btRwzyGZb",
	"UEznBN+82f500ID/nkb+9d8PvmFd9LTA8zZtfFcxTU2qWMKOA/Xz4Vishz41Xk6br8ke/otCCSQW9X8J",
	"IcZs8L9K3wQr6wma0IExGFYimIJVSEg6O72YJvC9j5Klql3gABU0FFU2gUNVVnTpuhqncwyLgqeFj0er",
	"6rToxyNJMSizoRg59wd4VJB8hTLpmwM4OJDK0P8ZBAefNRCmckCjQ/DldAi/a4OG3qT97TWleYP6dpho",
	"qJATkOEtClW5Yn3H4bVQxhJcR5lKzfN2rj0aaMjPtMrq1P+5a85T30c+3xiFs4on3XkU6RVOstFB81zC",
	"6n9BjmjUJwZzyYoS3ehkU8fD88sjUGFgkMAb94caZ93O/7hcsjNIZKTastWXxlfShSoFIN6iBoPomzW1",
	"CMVx2N/75O767r8BAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
